return {}
-- local M = {}
--
-- local state = {
-- 	buf = -1,
-- 	win = -1,
-- }
--
-- local function is_valid()
-- 	return vim.api.nvim_buf_is_valid(state.buf) and vim.api.nvim_win_is_valid(state.win)
-- end
--
-- local function create_float()
-- 	local width = math.floor(vim.o.columns * 0.8)
-- 	local height = math.floor(vim.o.lines * 0.8)
-- 	local col = math.floor((vim.o.columns - width) / 2)
-- 	local row = math.floor((vim.o.lines - height) / 2)
--
-- 	local buf = vim.api.nvim_create_buf(false, true)
-- 	local win = vim.api.nvim_open_win(buf, true, {
-- 		relative = "editor",
-- 		width = width,
-- 		height = height,
-- 		col = col,
-- 		row = row,
-- 		style = "minimal",
-- 		border = "rounded",
-- 		title = " Terminal ",
-- 		title_pos = "center",
-- 	})
--
-- 	return buf, win
-- end
--
-- function M.toggle()
-- 	if is_valid() then
-- 		vim.api.nvim_win_hide(state.win)
-- 		state.win = -1
-- 		return
-- 	end
--
-- 	local buf, win = create_float()
-- 	state.buf = buf
-- 	state.win = win
--
-- 	if vim.bo[buf].buftype ~= "terminal" then
-- 		vim.cmd.terminal()
-- 	end
--
-- 	vim.cmd.startinsert()
-- end
--
-- function M.setup(opts)
-- 	opts = opts or {}
-- 	local keymap = opts.keymap or "<leader>tt"
--
-- 	vim.keymap.set({ "n", "t" }, keymap, M.toggle, { desc = "Toggle terminal" })
-- end
--
-- return M
